name: iOS starter workflow

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Fastlane Action
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: beta
